inherit_from: .rubocop_todo.yml

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Layout/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15

Naming/HeredocDelimiterNaming:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/MethodMissingSuper:
  Exclude:
    - spec/support/silence_output.rb

Style/MissingRespondToMissing:
  Exclude:
    - spec/support/silence_output.rb

Style/RegexpLiteral:
  Exclude:
    - '**/*.gemspec'
    - '**/Guardfile'
